on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to build the house-finder container
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build the container house-finder
      id: build_house_finder
      run: docker build -t house-finder .
